### ISSUE TITLE
Coraza WAF Integration

### ISSUE THREAD

**Issue by superstes** [ansibleguy/infra_haproxy#4]
It would be nice if the role could handle the [Coraza WAF](https://github.com/corazawaf/coraza) Integration via [SPOA](https://github.com/corazawaf/coraza-spoa).

We would need:
* a flag to en- & disable the WAF management (by role)
* creation of the SPOA service
  * creation of a service-user
* list/dict of WAF applications
  * define exclusion-rules based on the application
  * log with application-name
  * adding a WAF-config per application (https://github.com/corazawaf/coraza-coreruleset)
  * en- & disabling of drops by application
* workaround for logging in JSON-format (related to https://github.com/corazawaf/coraza/issues/1151)

**Comment by superstes** [comment]
Note: It might be useful to abstract this handling into a separate role - in case others could benefit from it

**Comment by ansibleguy** [comment]
https://github.com/ansibleguy/haproxy_waf_coraza
